[window]
opacity = 0.9
decorations = 'None'
blur = true
startup_mode = 'Maximized'

[font]
size = 8
normal = { family = "Victor Mono Nerd Font", style = "SemiBold"}

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true
